import Header from '@/components/layout/Header'
import QueryProvider from '@/components/providers/QueryProvider'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import MusicPlayer from '../components/music-play/MusicPlayer'
import '../styles/globals.css'

const pretendard = localFont({
  src: '../assets/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '100 900',
  variable: '--font-pretendard',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.className}`}>
        <QueryProvider>
          <Header />
          <div className="h-screen w-full px-6">{children}</div>
          {/* Footer 잠시 주석처리 */}
          {/* <Footer /> */}
          <MusicPlayer />
        </QueryProvider>
      </body>
    </html>
  )
}
