import Header from '@/components/layout/Header'
import QueryProvider from '@/components/providers/QueryProvider'
import type { Metadata } from 'next'
import { ThemeProvider } from 'next-themes'
import localFont from 'next/font/local'
import MusicPlayer from '../components/music-play/MusicPlayer'
import '../styles/globals.css'

const pretendard = localFont({
  src: '../assets/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '100 900',
  variable: '--font-pretendard',
})

export const metadata: Metadata = {
  title: 'ZepPlaylist',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.className}`}>
        <QueryProvider>
          <ThemeProvider>
            <Header />

            <div className="h-full w-full px-6 pt-navBar bg-white">{children}</div>
            {/* Footer 잠시 주석처리 */}
            {/* <Footer /> */}
            <MusicPlayer />
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  )
}
